name: Build Kernel

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get UID and GID
        id: uid_gid
        run: |
          echo "UID=$(id -u)" >> $GITHUB_ENV
          echo "GID=$(id -g)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: sbc-rock-2f/kernel-builder:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: docker/kernel.Dockerfile
          build-args: |
            UID=${{ env.UID }}
            GID=${{ env.GID }}

      - name: List Docker images (debug)
        run: docker images

      - name: Build Kernel
        run: docker run --rm -v $(pwd):/workspace sbc-rock-2f/kernel-builder:latest ./compile.sh u-boot

      - name: Show output
        run: tree output

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-output
          path: |
            output/kernel/
            build/logs/
          retention-days: 7
